monolog:
  channels: ['nosto_scheduler']

  handlers:
    nostoSchedulerHandler:
      type: rotating_file
      path: "%kernel.logs_dir%/nosto_scheduler_%kernel.environment%.log"
      level: error
      channels: [ "nosto_scheduler" ]
